name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 12:05 AM UTC (5:35 AM IST)
    - cron: "5 0 * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
