name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 15 minutes between 6AM and 11PM UTC
    - cron: "*/15 6-23 * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
