name: Todoist Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 11:05 AM, 4:05PM and 11:05 PM UTC
    - cron: "5 11,16,23 * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""
